config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true do
        resources :answers, shallow: true
      end
    end

    resources :gists, only: %i[show index]

    resources :badges
  end

  resources :badges, only: %i[index]
  resources :feedback, only: %i[index create]
end

app/models/admin.rb
class Admin < User; end

app/models/answer.rb
class Answer < ApplicationRecord
  ANSWERS_LIMIT = 4

  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validate :validate_answer_count, on: :create

  private

  def validate_answer_count
    errors.add(:question, 'Exceeded answers limit') if question.answers.count > ANSWERS_LIMIT
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  RULE_TYPES = %i[all_tests_at_category passing_test_at_first_attempt all_tests_at_level]

  has_many :user, through: :user_test_badges
  has_many :test, through: :user_test_badges
  has_many :user_test_badges

  validates :title, presence: true
  validates :badge_type, presence: true
  validates :parameter, presence: true
  validates :image_url, presence: true

  attr_accessor :types

  def self.badge_types
    @types = RULE_TYPES
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests

  default_scope { order(:title) }

  validates :title, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: "User", foreign_key: 'user_id'
  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages
  has_many :user_test_badges, dependent: :destroy
  has_many :badge, through: :user_test_badges

  scope :by_level, -> (level) { where(level: level) }
  scope :easy, -> { by_level(1) }
  scope :intermediate, -> { by_level(2..4) }
  scope :hard, -> { by_level(5..Float::INFINITY) }

  scope :by_category_title, -> (title) { joins(:category).where('categories.title = :title', title: title) }

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, greater_than: 0 }, uniqueness: { scope: :title }
  validates :passage_time, numericality: { only_integer: true, greater_than: 0 }

  def self.by_title(title)
    Test
      .by_category_title(title)
      .order(title: :desc)
      .pluck(:title)
  end

  def has_timer?
    self.passage_time > 0
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS_RATE = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :set_question
  before_update :set_passed

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_question += 1
    end

    save
  end

  def passed?
    result >= SUCCESS_RATE
  end

  def result
    (self.correct_question.to_f / questions_count) * 100
  end

  def questions_count
    test.questions.count
  end

  def current_question_index
    test.questions.index(current_question) unless completed?
  end

  def remaining_time
    (self.test.passage_time - (Time.current - self.created_at).seconds).to_i
  end

  private

  def set_question
    if self.current_question.present?
      self.current_question = next_question
    else
      self.current_question = test.questions.first
    end
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort if answer_ids.present?
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def set_passed
    self.passed = passed? if completed?
  end
end

app/models/tests_user.rb
class TestsUser < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable

  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :created_tests, class_name: 'Test'
  has_many :gists
  has_many :user_test_badges, dependent: :destroy
  has_many :badge, through: :user_test_badges

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  def find_by_level(level)
    tests.by_level(level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def admin?
    is_a?(Admin)
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
  belongs_to :test
end

app/models/user_test_badge.rb
class UserTestBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
  belongs_to :test
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < ApplicationController
  before_action :set_badge, only: [:show, :edit, :update, :destroy]

  def index
    @badges = Badge.all
  end

  def show; end

  def new
    @badge = Badge.new
  end

  def edit; end

  def create
    @badge = Badge.new(badge_params)
    if @badge.save
      redirect_to admin_badges_path
    else
      render :new
    end
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badges_path
    else
      redirect_to :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private

  def set_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:title, :badge_type, :parameter, :image_url)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = Badge.all
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    DateTime.current.year
  end

  def github_url(author, repo, project_name)
    link_to "#{project_name}", "https://github.com/#{author}/#{repo}", target: '_blank'
  end

  def welcome_message(user)
    welcome = t('activerecord.welcome')
    "#{welcome} #{user.full_name}!".html_safe
  end

  def select_language
    is_default_local = I18n.locale == I18n.default_locale

    link_options = {
      title: is_default_local ? 'En' : 'Ру',
      lang: is_default_local ? 'en' : 'ру',
      class: current_user&.admin? ? 'nav-link text-white' : 'nav-link'
    }

    link_to link_options[:title], { lang: link_options[:lang] }, class: link_options[:class]
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shared_helper.rb
module SharedHelper
end

app/helpers/tests_helper.rb
module TestsHelper
  LEVELS = { 0 => :easy, 1 => :elementary, 2 => :advanced, 3 => :hard }.freeze

  def test_level(test)
    LEVELS[test.level] || :hero
  end
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td class="align-middle"><%= badge.title %></td>
  <td class="align-middle"><%= badge.badge_type %></td>
  <td class="align-middle"><%= badge.parameter %></td>
  <td class="align-middle"><%= octicon badge.image_url %></td>
  <td class="align-middle"><%= link_to t('admin.badges.show.show_button'), admin_badge_path(badge) %></td>
  <td class="align-middle">
    <%= link_to t('admin.badges.show.edit_button'), edit_admin_badge_path(badge) %>
  </td>
  <td class="align-middle">
    <%= link_to t('admin.badges.show.delete_button'),
                admin_badge_path(badge),
                method: :delete,
                data: { confirm: t('admin.badges.show.delete_confirmation') }
    %>
  </td>
</tr>

app/views/admin/badges/_form.html.erb
<div class="form-group">
  <%= form_with(model: [:admin, @badge], local: true) do |form| %>
    <%= render 'shared/errors', resource: @badge %>

    <div class="mb-3">
      <%= form.label :title, class: 'form-label' %><br>
      <%= form.text_field :title, id: :badge_name, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.label :badge_type, class: 'form-label' %><br>
      <%= form.select :badge_type, Badge.badge_types, { prompt: true }, { class: 'form-control' } %>
    </div>

    <div class="mb-3">
      <%= form.label :parameter, class: 'form-label' %>
      <%= form.text_field :parameter, id: :parameter, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.label :image_url, class: 'form-label' %>
      <%= form.select :image_url, Octicons::OCTICON_SYMBOLS.keys, { prompt: true }, { class: 'form-select' } %>
    </div>

    <div class="mb-3">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/admin/badges/edit.html.erb
<h2><%= t('.header', title: @badge.title) %></h2>

<%= render 'form' %>

<%= link_to t('helpers.page.back'), admin_badge_path %>

app/views/admin/badges/index.html.erb
<h1><%= t('.header') %>:</h1>

<p><%= link_to t('.new_badge'), new_admin_badge_path %></p>

<table class="table table-bordered">
  <thead class="thead">
  <tr>
    <th><%= t('.title') %></th>
    <th><%= t('.badge_type') %></th>
    <th><%= t('.parameter') %></th>
    <th><%= t('.badge_image') %></th>
    <th colspan="3"><%= t('.actions') %></th>
  </tr>
  </thead>
  <tbody>
  <%= render @badges %>
  </tbody>
</table>

app/views/admin/badges/new.html.erb
<h2><%= t('.header') %></h2>

<%= render 'form' %>

<%= link_to t('helpers.page.back'), admin_badges_path %>

app/views/admin/badges/show.html.erb
<h2><%= t('.header', id: @badge.id) %>:</h2>

<div class="mb-3">
  <div class="mb-3">
    <strong><%= t('.title') %>:</strong> <%= @badge.title %>
  </div>
  <div class="mb-3">
    <strong><%= t('.badge_type') %>:</strong> <%= @badge.badge_type %>
  </div>
  <div class="mb-3">
    <strong><%= t('.parameter') %>:</strong> <%= @badge.parameter %>
  </div>
  <div class="mb-3">
    <strong><%= t('.badge_image') %>:</strong> <%= @badge.image_url %>
  </div>
</div>

<%= link_to t('helpers.page.back'), admin_badges_path, class: 'link-primary' %> | <%= link_to t('admin.badges.show.edit'), edit_admin_badge_path(@badge) %>

app/views/badges/_badge.html.erb
<tr>
  <td class="align-middle"><%= badge.title %></td>
  <td class="align-middle"><%= badge.badge_type %></td>
  <td class="align-middle"><%= badge.parameter %></td>
  <td class="align-middle"><%= octicon badge.image_url %></td>
</tr>

app/views/badges/index.html.erb
<h1><%= t('.header') %>:</h1>

<%= render 'shared/errors', resource: @badge %>

<table class="table table-bordered">
  <thead class="thead">
  <tr>
    <th>
      <%= t('.name') %>
    </th>
    <th><%= t('.badge_type') %></th>
    <th><%= t('.parameter') %></th>
    <th><%= t('.badge_image') %></th>
  </tr>
  </thead>
  <tbody>
  <%= render current_user.badge.order(created_at: :desc) %>
  </tbody>
</table>