config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true do
        resources :answers, shallow: true
      end
    end

    resources :gists, only: %i[show index]

    resources :badges
  end

  resources :badges, only: %i[index]
  resources :feedback, only: %i[index create]
end

app/models/admin.rb
class Admin < User; end

app/models/answer.rb
class Answer < ApplicationRecord
  ANSWERS_LIMIT = 4

  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validate :validate_answer_count, on: :create

  private

  def validate_answer_count
    errors.add(:question, 'Exceeded answers limit') if question.answers.count > ANSWERS_LIMIT
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  RULE_TYPES = %i[all_tests_at_category passing_test_at_first_attempt all_tests_at_level]

  has_many :user, through: :user_test_badges
  has_many :test, through: :user_test_badges
  has_many :user_test_badges

  validates :title, presence: true
  validates :badge_type, presence: true
  validates :parameter, presence: true
  validates :image_url, presence: true

  attr_accessor :types

  def self.badge_types
    @types = RULE_TYPES
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests

  default_scope { order(:title) }

  validates :title, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: "User", foreign_key: 'user_id'
  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages
  has_many :user_test_badges, dependent: :destroy
  has_many :badge, through: :user_test_badges

  scope :by_level, -> (level) { where(level: level) }
  scope :easy, -> { by_level(1) }
  scope :intermediate, -> { by_level(2..4) }
  scope :hard, -> { by_level(5..Float::INFINITY) }

  scope :by_category_title, -> (title) { joins(:category).where('categories.title = :title', title: title) }

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, greater_than: 0 }, uniqueness: { scope: :title }
  validates :passage_time, numericality: { only_integer: true, greater_than: 0 }

  def self.by_title(title)
    Test
      .by_category_title(title)
      .order(title: :desc)
      .pluck(:title)
  end

  def has_timer?
    self.passage_time > 0
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS_RATE = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :set_question
  before_update :set_passed

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_question += 1
    end

    save
  end

  def passed?
    result >= SUCCESS_RATE
  end

  def result
    (self.correct_question.to_f / questions_count) * 100
  end

  def questions_count
    test.questions.count
  end

  def current_question_index
    test.questions.index(current_question) unless completed?
  end

  def remaining_time
    (self.test.passage_time - (Time.current - self.created_at).seconds).to_i
  end

  private

  def set_question
    if self.current_question.present?
      self.current_question = next_question
    else
      self.current_question = test.questions.first
    end
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort if answer_ids.present?
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def set_passed
    self.passed = passed? if completed?
  end
end

app/models/tests_user.rb
class TestsUser < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable

  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :created_tests, class_name: 'Test'
  has_many :gists
  has_many :user_test_badges, dependent: :destroy
  has_many :badge, through: :user_test_badges

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  def find_by_level(level)
    tests.by_level(level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def admin?
    is_a?(Admin)
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
  belongs_to :test
end

app/models/user_test_badge.rb
class UserTestBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
  belongs_to :test
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show update result gist]

  def show; end

  def result; end

  def update
    if @test_passage.remaining_time <= 0
      @test_passage.accept!(params[:answer_ids])

      send_mail(@test_passage)

      redirect_to result_test_passage_path(@test_passage)
    else
      @test_passage.accept!(params[:answer_ids])

      if @test_passage.completed?
        send_mail(@test_passage)

        BadgesService.new(@test_passage) if @test_passage.passed?

        redirect_to result_test_passage_path(@test_passage)
      else
        render :show
      end
    end
  end

  def send_mail(test)
    TestsMailer.completed_test(test).deliver_now
  end

  def gist
    response = GistQuestionService.new(@test_passage.current_question)
    response.call

    flash_options = if response.success?
                      gist = current_user.gists.create(gist_url: response.url, question: @test_passage.current_question)
                      { notice: t('.success', url: gist.gist_url) }
                    else
                      { notice: t('.failure') }
                    end

    redirect_to @test_passage, flash_options
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shared_helper.rb
module SharedHelper
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
  LEVELS = { 0 => :easy, 1 => :elementary, 2 => :advanced, 3 => :hard }.freeze

  def test_level(test)
    LEVELS[test.level] || :hero
  end
end

app/views/test_passages/result.html.erb
<h3><%= t('.header', title: @test_passage.test.title)%></h3>

<h3>
  <%= t('.score') %>:

  <span class="<%= @test_passage.passed? ? 'text-success' : 'text-danger' %>">
    <%= number_to_percentage(@test_passage.result, precision: 2) %>
  </span>
</h3>

<h4><%= t('.answered_correctly', correct_question: @test_passage.correct_question, questions_count: @test_passage.questions_count )%></h4>

<%= link_to t('helpers.page.main'), tests_path, class: "btn btn-primary"  %>

app/views/test_passages/show.html.erb
<h3><%= t('.header') %> <%= @test_passage.test.title %></h3>

<% if @test_passage.test.has_timer? %>
  <%= content_tag :div,
                  class: 'timer',
                  data: { remaining_time: @test_passage.remaining_time } do %>
    <%= content_tag :span, nil, class: 'timer_label' %>
  <% end %>
<% end %>

<% if @test_passage.test.questions.present? %>
  <div class="progress test-progress">
    <%= content_tag :div, '',
                    class: 'progress-bar bg-success',
                    id: 'test-progress',
                    data: { question_number: @test_passage.current_question_index,
                            questions_count: @test_passage.questions_count } %>
  </div>

  <p>
    <%= @test_passage.current_question.body %>
  </p>

  <%= form_with url: test_passage_path(@test_passage), id: :test_passages, local: true, method: :put do |form| %>
    <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :title, include_hidden: false do |b| %>
      <div class="form-check mb-3">
        <%= b.label do %>
          <%= b.check_box id: "answer_ids_#{b.object.id}", class: 'form-check-input' %>
          <%= b.object.title %>
        <% end %>
      </div>
    <% end %>

    <div class="mb-3">
      <%= link_to t('.gist'), gist_test_passage_path(@test_passage), method: :post, class: 'btn btn-outline-success' %>
    </div>

    <div class="mb-3">
      <p><%= form.submit t('.next'), class: 'btn btn-success' %></p>
    </div>
  <% end %>

  <%= javascript_pack_tag 'utilities/passage-progress.js' %>
<% else %>
  <div class="mt-4 mb-4">
    <h1><%= t('.questions_not_found') %></h1>
  </div>
<% end %>

<%= javascript_pack_tag 'utilities/timer.js' %>