config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true do
        resources :answers, shallow: true
      end
    end

    resources :gists, only: %i[show index]

    resources :badges
  end

  resources :badges, only: %i[index]
  resources :feedback, only: %i[index create]
end

app/models/admin.rb
class Admin < User; end

app/models/answer.rb
class Answer < ApplicationRecord
  ANSWERS_LIMIT = 4

  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validate :validate_answer_count, on: :create

  private

  def validate_answer_count
    errors.add(:question, 'Exceeded answers limit') if question.answers.count > ANSWERS_LIMIT
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  RULE_TYPES = %i[all_tests_at_category passing_test_at_first_attempt all_tests_at_level]

  has_many :user, through: :user_test_badges
  has_many :test, through: :user_test_badges
  has_many :user_test_badges

  validates :title, presence: true
  validates :badge_type, presence: true
  validates :parameter, presence: true
  validates :image_url, presence: true

  attr_accessor :types

  def self.badge_types
    @types = RULE_TYPES
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests

  default_scope { order(:title) }

  validates :title, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: "User", foreign_key: 'user_id'
  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages
  has_many :user_test_badges, dependent: :destroy
  has_many :badge, through: :user_test_badges

  scope :by_level, -> (level) { where(level: level) }
  scope :easy, -> { by_level(1) }
  scope :intermediate, -> { by_level(2..4) }
  scope :hard, -> { by_level(5..Float::INFINITY) }

  scope :by_category_title, -> (title) { joins(:category).where('categories.title = :title', title: title) }

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, greater_than: 0 }, uniqueness: { scope: :title }
  validates :passage_time, numericality: { only_integer: true, greater_than: 0 }

  def self.by_title(title)
    Test
      .by_category_title(title)
      .order(title: :desc)
      .pluck(:title)
  end

  def has_timer?
    self.passage_time > 0
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS_RATE = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :set_question
  before_update :set_passed

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_question += 1
    end

    save
  end

  def passed?
    result >= SUCCESS_RATE
  end

  def result
    (self.correct_question.to_f / questions_count) * 100
  end

  def questions_count
    test.questions.count
  end

  def current_question_index
    test.questions.index(current_question) unless completed?
  end

  def remaining_time
    (self.test.passage_time - (Time.current - self.created_at).seconds).to_i
  end

  private

  def set_question
    if self.current_question.present?
      self.current_question = next_question
    else
      self.current_question = test.questions.first
    end
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort if answer_ids.present?
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def set_passed
    self.passed = passed? if completed?
  end
end

app/models/tests_user.rb
class TestsUser < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable

  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :created_tests, class_name: 'Test'
  has_many :gists
  has_many :user_test_badges, dependent: :destroy
  has_many :badge, through: :user_test_badges

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  def find_by_level(level)
    tests.by_level(level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def admin?
    is_a?(Admin)
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
  belongs_to :test
end

app/models/user_test_badge.rb
class UserTestBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
  belongs_to :test
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shared_helper.rb
module SharedHelper
end

app/helpers/tests_helper.rb
module TestsHelper
  LEVELS = { 0 => :easy, 1 => :elementary, 2 => :advanced, 3 => :hard }.freeze

  def test_level(test)
    LEVELS[test.level] || :hero
  end
end

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, id: 'error_explanation', class: 'resource-errors', data: { resource_id: resource.id } do %>
    <p><%= t('.header', count: resource.errors.count) %>:</p>

    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash_errors.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <%= content_tag :div, msg.html_safe, id: "warning: #{name}" %>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="mt-auto text-lg-start bg-light text-muted">
  <div class="container">
    <div class="pt-4 pb-4">
      <%= link_to feedback_index_path do %>
        <%= octicon 'mail' %>
      <% end %>
      <br />
      <%= github_url('popeskul', 'test-guru', 'TestGuru') %> &copy; <%= current_year %>
      <div class="mb-3">Educational project at online-school <a href="//www.thinknetica.com" target="_blank">Thinknetica</a></div>
    </div>
  </div>
</footer>

app/views/shared/_footer.ru.html.erb
<footer class="mt-auto text-lg-start bg-light text-muted">
  <div class="container">
    <div class="pt-4 pb-4">
      <%= link_to feedback_index_path do %>
        <%= octicon 'mail' %>
      <% end %>
      <br />
      <%= github_url('popeskul', 'test-guru', 'TestGuru') %> &copy; <%= current_year %>
      <div>Образовательный проект онлайн-школы <a href="//www.thinknetica.com" target="_blank">Thinknetica</a></div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light  <%= current_user&.admin? ? 'text-white bg-primary' : '' %>">
  <div class="container">
    <%= link_to 'TestGuru', current_user&.admin? ? admin_tests_path : root_path, class: current_user&.admin? ? 'navbar-brand text-white' : 'navbar-brand' %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item"><b><%= welcome_message(current_user) %></b></li>
          <li class="nav-item"><%= current_user.email %></li>
          <li><%= link_to 'Badges', badges_path, class: 'badge bg-dark text-light' %></li>
        <% end %>
      </ul>

      <% if user_signed_in? %>
        <ul class="navbar-nav">
          <li class="nav-item"><%= link_to t('tests.index.header'), tests_path, class: current_user&.admin? ? 'nav-link text-white' : 'nav-link' %></li>
          <li class="nav-item"><%= link_to t('.exit'), destroy_user_session_path, method: :delete, class: current_user&.admin? ? 'nav-link text-white' : 'nav-link' %></li>
          <li><%= select_language %></li>
        </ul>
      <% else %>
        <ul class="navbar-nav">
          <li class="nav-item"><%= link_to t('.sign_up'), new_user_registration_path, class: current_user&.admin? ? 'nav-link text-white' : 'nav-link' %></li>
          <li class="nav-item"><%= link_to t('.sign_in'), new_user_session_path, class: current_user&.admin? ? 'nav-link text-white' : 'nav-link' %></li>
          <li><%= select_language %></li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>